
project:
  type: website
  output-dir: site

website:
  title: "SAVED project documentation"
  open-graph: true
  site-url: https://marine.gov.scot/metadata/saved/
  repo-url: https://github.com/saved-models/doc/
  issue-url: https://github.com/saved-models/doc/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: saved/doc/misc/outline.md
      - text: "Project documentation"
        href: saved/doc/utils/index.md
      - text: "Data model / ontology"
        href: saved/schema/index.md

  sidebar:
    - id: utils
      title: "Project documentation"
      style: "floating"
      collapse-level: 5
      align: left
      contents:
        - section: "Project outline"
          contents:
            - saved/doc/misc/outline.md
        - section: "Fish data utilities"
          contents:
            - saved/doc/utils/index.md
            - saved/doc/utils/schemata.md
            - saved/doc/utils/manifest.md
            - saved/doc/utils/debugging.md
    - id: ontology
      title: "Data model / ontology"
      style: "floating"
      collapse-level: 5
      align: left
      contents:
        - saved/schema/index.md

#bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    #include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

freeze: true

editor: visual

profile:
  group: 
    - [rc,prerelease]
