# All generators: https://linkml.io/linkml/_modules/linkml/generators/projectgen.html
generator_args:
  python:
    genmeta: True
    mergeimports: False
excludes:
  - markdown  # gen-doc is run separately
  - python    # gen-python is run separately for each source YAML file
  - graphql
  - markdown
  - proto
  - shex
  - shacl
  - sqltable
  - excel
