# All generators: https://linkml.io/linkml/_modules/linkml/generators/projectgen.html
generator_args:
  python:
    genmeta: True
    mergeimports: False
excludes:
  - python # gen-python is run separately for each source YAML file
  - graphql
  - proto
  - shex
  - shacl
  - sqltable
  - excel

# - python   
# - markdown # gen-doc is run separately
