site_name: "SAVED project schema"
theme:
  name: material
  features:
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home:  index.md
  - Index: index.md
site_url: http://marine.gov.scot/metadata/saved/schema/
repo_url: https://github.com/saved-models/data-model
