id: http://localhost/saved/schema/meta/
name: meta
title: >-
  SAVED meta-model
prefixes:
  dcterms: http://purl.org/dc/terms/
  linkml:  https://w3id.org/linkml/
  rap:     http://localhost/saved/rap/
  saved:   http://localhost/saved/schema/
  job:     http://localhost/saved/schema/job_
imports:
  - linkml:types
  - saved:core
  - saved:collected
  - saved:descriptive
  - saved:job
  - saved:modelled
default_prefix: saved

emit_prefixes:
  - rap
  - saved
  - job
