id: http://marine.gov.scot/metadata/saved/schema/meta/
name: meta
title: >-
  SAVED meta-model
prefixes:
  linkml: https://w3id.org/linkml/
  saved:  http://marine.gov.scot/metadata/saved/schema/
imports:
  - linkml:types
  - ./core
  - ./collected
  - ./descriptive
  - ./job
  - ./modelled
default_prefix: saved

emit_prefixes:
  saved
