project:
  type:       website
  output-dir: ../site

website:
  title:           "SAVED project documentation"
  open-graph:      true
  site-url:        https://marine.gov.scot/metadata/saved/
  repo-url:        https://github.com/saved-models/data-model/
  issue-url:       https://github.com/saved-models/data-model/issues/new/choose
  repo-actions:    issue
  page-navigation: true
  bread-crumbs:    true
  search:
    show-item-context: true
    type: overlay
  navbar:
    background:     light
    title:          false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.md
      - text: "Project documentation"
        menu:
          - text: "Project outline"
            href: doc/misc/outline.md
          - text: "Fish data utilities"
            href: doc/utils/index.md
      - text: "Data model / ontology"
        href: schema/index.md
      - text: "RAP results"
        href: rap/index.md

  sidebar:
    - id:             utils
      title:          "Project documentation"
      style:          "floating"
      collapse-level: 5
      align:          left
      contents:
        #- section: "Project outline"
        #  contents:
        #    - doc/misc/outline.md
        - text:    "Project outline"
          href:    doc/misc/outline.md
        - section: "Fish data utilities"
          contents:
            - doc/utils/index.md
            - doc/utils/schemata.md
            - doc/utils/manifest.md
            - doc/utils/debugging.md

#bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: cosmo
    code-copy:     true
    code-overflow: wrap
    #include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width:    900px
      margin-width:  300px

freeze: true

editor: visual

profile:
  group: 
    - [rc,prerelease]
